### ISSUE TITLE
Demo Planning

### ISSUE THREAD

**Issue by QuincyMillerDev** [uconndxlab/landscape-AR#45]
### From Parent #34 

This ticket is a place for all of our notes from the meeting with Parker, Quincy, and Jon about the exact deliverables we want to present for our upcoming demo.

**Comment by QuincyMillerDev** [comment]
Step by step of how we want the demo to go:
1. A user uploads a 3D model to the web app (.obj file)
2. They use the app to convert to a topographic map
3. The app displays the topographic map

Required workload:
- File uploading on the backend
- Bare minimum UI for file upload and topographic map display
- Find a test 3D model we want to use for the demo
- Fleshing out the 3D model -> topographic map conversion (specifically turning the matrix result of the conversion scripts into a viable final product.)

Notes:
- For now the user functionality does not need to have full authentication, we dont even really need to represent a user
- Could possibly expand to 3D render the uploaded obj file but that is low priority

**Comment by joelsalisbury** [comment]
Nice. This is 100% what I had in mind. This way, the demo is extensible: when we come up with a new discrete feature like a new conversion script (say, topo to 3D, or even some sort of photo processing), we can just add it to the menu. 

With this approach, we can use the demo to guide the discussion with Mariana, asking her things like

- What other conversions do we need to create? (I'll dig through the notes and see if we can come up with this list btw, I think we might have already done some of this research)
- What do we need to change about the results of these conversion scripts?

... and once we have a "suite" of tools that do the random image conversions, we can talk about how we're going to make it "cooler" with realtime rendering, AR functionality, etc.

Long way of saying, I think this would be great demo.

**Comment by QuincyMillerDev** [comment]
ALSO: mockups for UI https://xd.adobe.com/view/ba6401ab-50e3-4af1-af2e-a0e9b314ec91-ef37/
